/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
#if !SILVERLIGHT
using System.Xml.Serialization;
#endif
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace MVI.DotnetSoftwarePlatform.Api.Thrift
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  [DataContract(Namespace="")]
  public partial class TAccount : TBase
  {
    private string _UniqueName;
    private string _Password;
    private long _CreatedAt;
    private long _UpdatedAt;
    private string _Remark;
    private bool _IsEnabled;
    private List<TRole> _Roles;

    [DataMember(Order = 0)]
    public string UniqueName
    {
      get
      {
        return _UniqueName;
      }
      set
      {
        __isset.UniqueName = true;
        this._UniqueName = value;
      }
    }

    [DataMember(Order = 0)]
    public string Password
    {
      get
      {
        return _Password;
      }
      set
      {
        __isset.Password = true;
        this._Password = value;
      }
    }

    [DataMember(Order = 0)]
    public long CreatedAt
    {
      get
      {
        return _CreatedAt;
      }
      set
      {
        __isset.CreatedAt = true;
        this._CreatedAt = value;
      }
    }

    [DataMember(Order = 0)]
    public long UpdatedAt
    {
      get
      {
        return _UpdatedAt;
      }
      set
      {
        __isset.UpdatedAt = true;
        this._UpdatedAt = value;
      }
    }

    [DataMember(Order = 0)]
    public string Remark
    {
      get
      {
        return _Remark;
      }
      set
      {
        __isset.Remark = true;
        this._Remark = value;
      }
    }

    [DataMember(Order = 0)]
    public bool IsEnabled
    {
      get
      {
        return _IsEnabled;
      }
      set
      {
        __isset.IsEnabled = true;
        this._IsEnabled = value;
      }
    }

    [DataMember(Order = 0)]
    public List<TRole> Roles
    {
      get
      {
        return _Roles;
      }
      set
      {
        __isset.Roles = true;
        this._Roles = value;
      }
    }


    [XmlIgnore] // XmlSerializer
    [DataMember(Order = 1)]  // XmlObjectSerializer, DataContractJsonSerializer, etc.
    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    [DataContract]
    public struct Isset {
      [DataMember]
      public bool UniqueName;
      [DataMember]
      public bool Password;
      [DataMember]
      public bool CreatedAt;
      [DataMember]
      public bool UpdatedAt;
      [DataMember]
      public bool Remark;
      [DataMember]
      public bool IsEnabled;
      [DataMember]
      public bool Roles;
    }

    #region XmlSerializer support

    public bool ShouldSerializeUniqueName()
    {
      return __isset.UniqueName;
    }

    public bool ShouldSerializePassword()
    {
      return __isset.Password;
    }

    public bool ShouldSerializeCreatedAt()
    {
      return __isset.CreatedAt;
    }

    public bool ShouldSerializeUpdatedAt()
    {
      return __isset.UpdatedAt;
    }

    public bool ShouldSerializeRemark()
    {
      return __isset.Remark;
    }

    public bool ShouldSerializeIsEnabled()
    {
      return __isset.IsEnabled;
    }

    public bool ShouldSerializeRoles()
    {
      return __isset.Roles;
    }

    #endregion XmlSerializer support

    public TAccount() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String) {
                UniqueName = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                Password = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.I64) {
                CreatedAt = iprot.ReadI64();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.I64) {
                UpdatedAt = iprot.ReadI64();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 5:
              if (field.Type == TType.String) {
                Remark = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 6:
              if (field.Type == TType.Bool) {
                IsEnabled = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 7:
              if (field.Type == TType.List) {
                {
                  Roles = new List<TRole>();
                  TList _list4 = iprot.ReadListBegin();
                  for( int _i5 = 0; _i5 < _list4.Count; ++_i5)
                  {
                    TRole _elem6;
                    _elem6 = new TRole();
                    _elem6.Read(iprot);
                    Roles.Add(_elem6);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("TAccount");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (UniqueName != null && __isset.UniqueName) {
          field.Name = "UniqueName";
          field.Type = TType.String;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(UniqueName);
          oprot.WriteFieldEnd();
        }
        if (Password != null && __isset.Password) {
          field.Name = "Password";
          field.Type = TType.String;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Password);
          oprot.WriteFieldEnd();
        }
        if (__isset.CreatedAt) {
          field.Name = "CreatedAt";
          field.Type = TType.I64;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteI64(CreatedAt);
          oprot.WriteFieldEnd();
        }
        if (__isset.UpdatedAt) {
          field.Name = "UpdatedAt";
          field.Type = TType.I64;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          oprot.WriteI64(UpdatedAt);
          oprot.WriteFieldEnd();
        }
        if (Remark != null && __isset.Remark) {
          field.Name = "Remark";
          field.Type = TType.String;
          field.ID = 5;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Remark);
          oprot.WriteFieldEnd();
        }
        if (__isset.IsEnabled) {
          field.Name = "IsEnabled";
          field.Type = TType.Bool;
          field.ID = 6;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(IsEnabled);
          oprot.WriteFieldEnd();
        }
        if (Roles != null && __isset.Roles) {
          field.Name = "Roles";
          field.Type = TType.List;
          field.ID = 7;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.Struct, Roles.Count));
            foreach (TRole _iter7 in Roles)
            {
              _iter7.Write(oprot);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that) {
      var other = that as TAccount;
      if (other == null) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.UniqueName == other.__isset.UniqueName) && ((!__isset.UniqueName) || (System.Object.Equals(UniqueName, other.UniqueName))))
        && ((__isset.Password == other.__isset.Password) && ((!__isset.Password) || (System.Object.Equals(Password, other.Password))))
        && ((__isset.CreatedAt == other.__isset.CreatedAt) && ((!__isset.CreatedAt) || (System.Object.Equals(CreatedAt, other.CreatedAt))))
        && ((__isset.UpdatedAt == other.__isset.UpdatedAt) && ((!__isset.UpdatedAt) || (System.Object.Equals(UpdatedAt, other.UpdatedAt))))
        && ((__isset.Remark == other.__isset.Remark) && ((!__isset.Remark) || (System.Object.Equals(Remark, other.Remark))))
        && ((__isset.IsEnabled == other.__isset.IsEnabled) && ((!__isset.IsEnabled) || (System.Object.Equals(IsEnabled, other.IsEnabled))))
        && ((__isset.Roles == other.__isset.Roles) && ((!__isset.Roles) || (TCollections.Equals(Roles, other.Roles))));
    }

    public override int GetHashCode() {
      int hashcode = 0;
      unchecked {
        hashcode = (hashcode * 397) ^ (!__isset.UniqueName ? 0 : (UniqueName.GetHashCode()));
        hashcode = (hashcode * 397) ^ (!__isset.Password ? 0 : (Password.GetHashCode()));
        hashcode = (hashcode * 397) ^ (!__isset.CreatedAt ? 0 : (CreatedAt.GetHashCode()));
        hashcode = (hashcode * 397) ^ (!__isset.UpdatedAt ? 0 : (UpdatedAt.GetHashCode()));
        hashcode = (hashcode * 397) ^ (!__isset.Remark ? 0 : (Remark.GetHashCode()));
        hashcode = (hashcode * 397) ^ (!__isset.IsEnabled ? 0 : (IsEnabled.GetHashCode()));
        hashcode = (hashcode * 397) ^ (!__isset.Roles ? 0 : (TCollections.GetHashCode(Roles)));
      }
      return hashcode;
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("TAccount(");
      bool __first = true;
      if (UniqueName != null && __isset.UniqueName) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("UniqueName: ");
        __sb.Append(UniqueName);
      }
      if (Password != null && __isset.Password) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Password: ");
        __sb.Append(Password);
      }
      if (__isset.CreatedAt) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("CreatedAt: ");
        __sb.Append(CreatedAt);
      }
      if (__isset.UpdatedAt) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("UpdatedAt: ");
        __sb.Append(UpdatedAt);
      }
      if (Remark != null && __isset.Remark) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Remark: ");
        __sb.Append(Remark);
      }
      if (__isset.IsEnabled) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("IsEnabled: ");
        __sb.Append(IsEnabled);
      }
      if (Roles != null && __isset.Roles) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Roles: ");
        __sb.Append(Roles);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
