/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
#if !SILVERLIGHT
using System.Xml.Serialization;
#endif
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace MVI.DotnetSoftwarePlatform.Api.Thrift
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class TAlreadyExistException : TException, TBase
  {
    private string _Reason;

    [DataMember(Order = 0)]
    public string Reason
    {
      get
      {
        return _Reason;
      }
      set
      {
        __isset.Reason = true;
        this._Reason = value;
      }
    }


    [XmlIgnore] // XmlSerializer
    [DataMember(Order = 1)]  // XmlObjectSerializer, DataContractJsonSerializer, etc.
    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    [DataContract]
    public struct Isset {
      [DataMember]
      public bool Reason;
    }

    #region XmlSerializer support

    public bool ShouldSerializeReason()
    {
      return __isset.Reason;
    }

    #endregion XmlSerializer support

    public TAlreadyExistException() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String) {
                Reason = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("TAlreadyExistException");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Reason != null && __isset.Reason) {
          field.Name = "Reason";
          field.Type = TType.String;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Reason);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that) {
      var other = that as TAlreadyExistException;
      if (other == null) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.Reason == other.__isset.Reason) && ((!__isset.Reason) || (System.Object.Equals(Reason, other.Reason))));
    }

    public override int GetHashCode() {
      int hashcode = 0;
      unchecked {
        hashcode = (hashcode * 397) ^ (!__isset.Reason ? 0 : (Reason.GetHashCode()));
      }
      return hashcode;
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("TAlreadyExistException(");
      bool __first = true;
      if (Reason != null && __isset.Reason) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Reason: ");
        __sb.Append(Reason);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }


  #if !SILVERLIGHT
  [Serializable]
  #endif
  [DataContract]
  public partial class TAlreadyExistExceptionFault
  {
    private string _Reason;

    [DataMember(Order = 0)]
    public string Reason
    {
      get
      {
        return _Reason;
      }
      set
      {
        this._Reason = value;
      }
    }

  }

}
